### PR TITLE
Feature/events

### PR DESCRIPTION
**Pull request by Nasa28**
This is a prototype of the Eventbrite app where registered members can create an event view and attend other people's events. Built with:
- Ruby on Rails
- Bootstrap
- Capybara
- Rspec

### CODE REVIEW

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @Nasa28  :wave: 

You've done well so far :+1:  and I commend you for that :clap: 
However, there are still some changes to be made before this milestone can be approved.

## REQUIRED

* [x] Webpacker is needed to run your project. Kindly add it to the **installation** steps in your README.
* [x] There's a typo on your index page. You have `Create and account` instead of `Create an account`.
* [x] You didn't specify if the user should enter their email or username
image
- [x] A logged-in user should be able to create a past event.







## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Changes required:wrench::hammer::full_moon:
**Hi Agu!
Great job so far:clap::clap:.** 
However, we still need to make a few changes to get this project approved:muscle:.

**To improve**
- [ ] Logged in user can create new event ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_can_create_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations)). Currently, I can't create an `event`. See [screen-shot](https://imgur.com/a/2FRuUmQ) for reference. Kindly fix the bug. I guess the bug was introduced during making changes from the first review. 

Make the above-required changes and when you are ready, request another review.

Do have questions/comments? kindly drop them :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan.

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Impressive work.  💻 👀 ✨
- Great work allowing users to create events as the previous CR requested.

## However, there are some changes required 👀 🧰 🔨 🔧
- When I create an event that is one day from the current date, the app classifies this as a "Previous event". Please test and fix this bug.
- On the User's `show` page, I see a complete list of all the events created by all the users. Instead, I should see a list of only the events created by the user. Please fix this.
- Your app does not have an events `show` page. Please add a page that displays all the events, but instead of linking it through the username, add another link to your app such as `Events`. In fact, you already have a page just like this, you've only mislabeled it as the user's `show` page.

***[ OPTIONAL: ]***
- Your app has great input validation, but it never reports to the user what went wrong when they submit a form with invalid input. You may add some error reporting to the page to fix this.

### Submit these changes and request a new code review! 😄 👍

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier)🧑‍💻🗨️🧑‍💻
# Happy Coding! 🧠 ⌨️ 🖱️ 🖥️

**Review by voscarmv — APPROVED** [review]
# Project status: Approved 💯 ✨ 😎 👍 
### You may merge this branch and move forward ⛙🛣️ 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻
# Happy Coding! 🧠 ⌨️ 🖱️ 🖥️

**Pull request merged**
